version: '3.8'

services:
  workflow-api:
    image: workflow-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress  # Load balancing across replicas
    environment:
      - PORT=5000
      - GITHUB_PULL_API=http://github-pull-api:4000
      - CLAUDE_CODE_API=http://claude-code-api:3000
      - NODE_ENV=production
    volumes:
      - workspace:/workspace
    networks:
      - workflow-network
    deploy:
      replicas: 5
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0  # Unlimited restarts
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "256M"
      placement:
        max_replicas_per_node: 5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  github-pull-api:
    image: github-pull-api:latest
    build:
      context: ../github-pull-api
      dockerfile: Dockerfile
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: ingress
    environment:
      - PORT=4000
      - WORKSPACE_DIR=/workspace
      - NODE_ENV=production
    volumes:
      - workspace:/workspace
    networks:
      - workflow-network
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "256M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  claude-code-api:
    image: claude-code-api:latest
    build:
      context: ../claude-code-api
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    environment:
      - PORT=3000
      - WORKSPACE_DIR=/workspace
      - NODE_ENV=production
      - CLAUDE_CODE_CREDENTIALS_SECRET=/run/secrets/claude_credentials
    secrets:
      - claude_credentials
    volumes:
      - workspace:/workspace
    networks:
      - workflow-network
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
        reservations:
          cpus: "0.5"
          memory: "512M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  workspace:
    driver: local

networks:
  workflow-network:
    driver: overlay
    attachable: true

secrets:
  claude_credentials:
    external: true
